### ISSUE TITLE
runserver直接报错了，求帮助

### ISSUE THREAD

**Issue by 0x0021** [JoneXiong/DjangoX#1]
bogon:example admin$ ./run.sh 
Unhandled exception in thread started by <function wrapper at 0x1027c7050>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/admin/PycharmProjects/DjangoX/example/../xadmin/__init__.py", line 18, in <module>
    from xadmin.sites import site
  File "/Users/admin/PycharmProjects/DjangoX/example/../xadmin/sites.py", line 10, in <module>
    from django.utils.datastructures import SortedDict

**Comment by JoneXiong** [comment]
你的django版本多少？
`from django.utils.datastructures import SortedDict`
这个v1.5之后一般都可以的

**Comment by 0x0021** [comment]
1.8  1.9试了都不行  不知道为什么

**Comment by JoneXiong** [comment]
已修复，兼容到 1.8 和 1.9 了
