### ISSUE TITLE
detail显示错误

### ISSUE THREAD

**Issue by zhuzhuhero** [JoneXiong/DjangoX#10]
Internal Server Error: /xadmin/auth/permission/59/detail/
Traceback (most recent call last):
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 215, in render
    c = self.get_render(context)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 134, in get_render
    actual_form.form_html = helper.render_layout(actual_form, node_context, template_pack=self.template_pack)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/helper.py", line 297, in render_layout
    template_pack=template_pack
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 138, in render
    return self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 102, in get_rendered_fields
    for field in self.fields
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 102, in <genexpr>
    for field in self.fields
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/utils.py", line 73, in render_field
    form, form_style, context, template_pack=template_pack,
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 358, in render
    fields = self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 102, in get_rendered_fields
    for field in self.fields
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 102, in <genexpr>
    for field in self.fields
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/utils.py", line 73, in render_field
    form, form_style, context, template_pack=template_pack,
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 358, in render
    fields = self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 102, in get_rendered_fields
    for field in self.fields
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 102, in <genexpr>
    for field in self.fields
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/utils.py", line 73, in render_field
    form, form_style, context, template_pack=template_pack,
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 285, in render
    fields = self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 102, in get_rendered_fields
    for field in self.fields
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/layout.py", line 102, in <genexpr>
    for field in self.fields
  File "/Users/zhulin/py2dj/lib/python2.7/site-packages/crispy_forms/utils.py", line 73, in render_field
    form, form_style, context, template_pack=template_pack,
TypeError: render() got an unexpected keyword argument 'template_pack'

**Comment by zhuzhuhero** [comment]
django==1.9
crispy_forms==1.6

**Comment by zhuzhuhero** [comment]
经测试，
django==1.7
crispy_forms==1.4 不会出现此错误

**Comment by JoneXiong** [comment]
谢谢反馈，会尽快查找修复的

**Comment by JoneXiong** [comment]
已修复
