### ISSUE TITLE
示例程序删除内容类型（content type）数据时报错

### ISSUE THREAD

**Issue by zhwei820** [JoneXiong/DjangoX#4]
重现操作：示例程序里面 =》 其他 =》 内容类型 =》 删除一条记录

ps. 对空的数据库进行migrate时也会出现类似的错误 （TypeError: int() argument must be a string or a number, not 'ContentType'）

traceback:

Internal Server Error: /xadmin/contenttypes/contenttype/
Traceback (most recent call last):
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/sites.py", line 454, in wrapper
    return self.site_view_decor(view, cacheable)(*args, **kwargs)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/sites.py", line 285, in inner
    return view(request, *args, **kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/views/base.py", line 331, in view
    return handler(request, *args, **kwargs)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/admin/back/DjangoX/example/../xadmin/views/structs.py", line 45, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/views/structs.py", line 13, in filter_chain
    return func()
  File "/home/admin/back/DjangoX/example/../xadmin/views/structs.py", line 39, in _inner_method
    return func(self, *args, **kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/views/list.py", line 279, in post
    return self.post_result_list() or self.post_response(*args, **kwargs) or self.get(request, *args, **kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/views/structs.py", line 45, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/views/structs.py", line 28, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/views/structs.py", line 13, in filter_chain
    return func()
  File "/home/admin/back/DjangoX/example/../xadmin/views/structs.py", line 27, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/plugins/actions.py", line 117, in post_response
    ret = self._response_action(ac, queryset)
  File "/home/admin/back/DjangoX/example/../xadmin/plugins/actions.py", line 131, in _response_action
    return action_view.do_action(queryset)
  File "/home/admin/back/DjangoX/example/../xadmin/views/structs.py", line 45, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/views/structs.py", line 13, in filter_chain
    return func()
  File "/home/admin/back/DjangoX/example/../xadmin/views/structs.py", line 39, in _inner_method
    return func(self, *args, **kwargs)
  File "/home/admin/back/DjangoX/example/../xadmin/views/action_delete.py", line 52, in do_action
    queryset, self.opts, self.user, self.admin_site, using)
  File "/home/admin/back/DjangoX/example/../xadmin/util.py", line 201, in get_deleted_objects
    collector.collect(objs)
  File "/home/admin/back/DjangoX/example/../xadmin/util.py", line 252, in collect
    return super(NestedObjects, self).collect(objs, source_attr=source_attr, **kwargs)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 225, in collect
    sub_objs = self.related_objects(related, batch)
  File "/home/admin/back/DjangoX/example/../xadmin/util.py", line 257, in related_objects
    qs = super(NestedObjects, self).related_objects(related, objs)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 245, in related_objects
    **{"%s__in" % related.field.name: objs}
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1310, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1338, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1200, in build_filter
    lookups, value)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1763, in get_lookup_constraint
    root_constraint.add(lookup_class(targets[0].get_col(alias, sources[0]), value), AND)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 105, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 143, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 729, in get_prep_lookup
    return [self.get_prep_value(v) for v in value]
  File "/home/admin/back/py2env/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 985, in get_prep_value
    return int(value)
TypeError: int() argument must be a string or a number, not 'ContentType'

**Comment by JoneXiong** [comment]
@zhwei820 已修复，感谢反馈
